### ISSUE TITLE
Blink not work

### ISSUE THREAD

**Issue by mathben** [prof7bit/bare_metal_stm32f401xe#2]
Hi, I am on arch linux and I have a Nucleo STM32F401RE

The compilation work and transfert too.
What is the difference with stm32f401xe and stm32f401re?

Thanks

>  # make install
> 
> [CC] src/main.c:
> arm-none-eabi-gcc -MMD -c -o build/src/main.o -Isrc/STM32F401XE  -ffunction-sections -mlittle-endian -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=gnu11 -ggdb -Os -flto -Wall -Wextra -Wstrict-prototypes -Werror -Wno-error=unused-function -Wno-error=unused-variable -Wfatal-errors -Warray-bounds -Wno-unused-parameter src/main.c
> 
> [LD] build/hello_world.elf:
> arm-none-eabi-gcc -o build/hello_world.elf build/src/STM32F401XE/gcc_startup_system.o build/src/main.o -ffunction-sections -mlittle-endian -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=gnu11 -ggdb -Os -flto --specs=nano.specs  --specs=nosys.specs  -nostartfiles -Wl,--gc-sections -Tsrc/STM32F401XE/gcc_linker.ld -lm -Wl,-Map=build/hello_world.map
> 
> [objcopy] build/hello_world.hex:
> arm-none-eabi-objcopy -O ihex -S build/hello_world.elf build/hello_world.hex
> 
> [OpenOCD] program build/hello_world.hex:
> openocd -d0 \
> -f board/st_nucleo_f4.cfg \
>   -c "program build/hello_world.hex" \
>   -c "reset run" \
>   -c "shutdown"
> Open On-Chip Debugger 0.9.0 (2016-04-27-23:18)
> Licensed under GNU GPL v2
> For bug reports, read
>   http://openocd.org/doc/doxygen/bugs.html
> debug_level: 0
> adapter speed: 2000 kHz
> adapter_nsrst_delay: 100
> none separate
> srst_only separate srst_nogate srst_open_drain connect_deassert_srst
> target state: halted
> target halted due to debug-request, current mode: Thread 
> xPSR: 0x01000000 pc: 0x080001bc msp: 0x20018000
> *\* Programming Started **
> auto erase enabled
> target state: halted
> target halted due to breakpoint, current mode: Thread 
> xPSR: 0x61000000 pc: 0x20000042 msp: 0x20018000
> wrote 16384 bytes from file build/hello_world.hex in 0.687820s (23.262 KiB/s)
> *\* Programming Finished **
> shutdown command invoked

**Comment by prof7bit** [comment]
can you please pull the latest changes and try again?

**Comment by mathben** [comment]
As soon as I can. I need to find where I putted the board...
